# Stage 1 - Build
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY Aarthrakshak/pom.xml ./pom.xml
COPY Aarthrakshak/src ./src
RUN mvn clean package -DskipTests

# Stage 2 - Run
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/Aarthrakshak-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]